apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s-dev/*
      # - ./k8s/client-deployment.yml
      # - ./k8s/server-deployment.yml
      # - ./k8s/worker-deployment.yml
      # - ./k8s/database-persistent-volume-claim.yml
      # - ./k8s/ingress-service.yml
      # - ./k8s/postgres-cluster-ip-service.yml
      # - ./k8s/postgres-deployment.yml
      # - ./k8s/redis-cluster-ip-service.yml
      # - ./k8s/redis-deployment.yml
      # - ./k8s/worker-deployment.yml
      # - ./k8s/server-cluster-ip-service.yml
      # - ./k8s/client-cluster-ip-service.yml
build:
  local:
    push: false
  artifacts:
    - image: spoonobi/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: spoonobi/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
          - src: "*.ts"
            dest: .
    - image: spoonobi/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
          - src: "*.ts"
            dest: .

      